
platform :ios, '11.0'

target 'breiv' do
  use_frameworks!
	
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyDrop'
  pod 'SwiftSpinner'
	
  target 'breivTests' do
    inherit! :search_paths
  end

  target 'breivUITests' do
    inherit! :search_paths
  end

end
